# Generated by Django 6.0.4 on 2026-04-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField()),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], max_length=16)),
                ('reference_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entry',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='ledger_entr_merchan_620720_idx'), models.Index(fields=['reference_id'], name='ledger_entr_referen_41698c_idx')],
            },
        ),
    ]
